name: learn-github-actions
#on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  check-ubuntu-version:
    runs-on: 
      - self-hosted
      - label-1
    steps:
      - uses: actions/checkout@v3
      - run: uname -m
      - run: docker -v
      - run: mkdir gitcode
      - run: cd gitcode
      - run: ls
      - run: git pull origin main
