name: demo github actions
#on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  ubuntu:
    runs-on: 
      - self-hosted
      - label-1
    steps:
      - uses: actions/checkout@v3
      - run: uname -m
      - run: docker -v
      - run: ls
      - run: git pull origin main
      - run: |
             cat test1
             cat test2
             cat test3
  pubuntu:
    runs-on: 
      - self-hosted
      - javaversion
    steps:
      - uses: actions/checkout@v3
      - run: uname -m
      - run: java -version
      - run : dir
      - run: git pull origin main
      - run : |
              cat test4
              cat test5
