name: demo github actions
#on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  windows1:
    runs-on: 
      - Agent_1
    steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           distribution: temurin
#           java-version: '11'        
#           java-package: jdk
#           server-id: github
#           jdkFile: C:\Program Files\Java\jdk-1.8
#       - name: Install Maven
#   # You may pin to the exact commit or the version.
#   # uses: yuzhiyongcn/setup-maven@0c5810c65a0fb6c88b6089724cc47370cf4eaffc
#         uses: yuzhiyongcn/setup-maven@v1.0.0
#         with:
#     # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
#           maven-version: 3.8.2
#       - name: Execute tests
#         run: |
#              cd democalculator
#              java -jar cucumber-tc-execution-engine-1.0.jar Agent_1 --spring.config.location=application10.properties
#       - name: Merge reports
#         run: |
#              cd democalculator
#              java -jar merge-cucumber-jar.jar  C:\\actions-runner\\_work\\GithubActionDemo\\GithubActionDemo\\democalculator\\target\\cucumber-reports Agent_1
        - name: Send email
          uses: devellany/send-mail@v1.0.2
          with:
           host: smtp.gmail.com
           account: ${{secrets.MAIL_ADDRESS}}
           password: ${{secrets.MAIL_PASSWORD}}
           sender: arun
           from: ${{secrets.MAIL_ADDRESS}}
           subject: Github Actions job result
           body: json file
           attachments: C:\\actions-runner\\_work\\GithubActionDemo\\GithubActionDemo\\democalculator\\target\\cucumber-reports\\Agent_1 2023-05-26 05-33-54_report.json
           to: bharat.nakka@cigniti.com
        
                        
#   windows2:
#     runs-on: 
#       - Agent_2
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           distribution: temurin
#           java-version: '11'        
#           java-package: jdk
#           server-id: github
#           jdkFile: C:\Program Files\Java\jdk-1.8
#       - name: Install Maven
#   # You may pin to the exact commit or the version.
#   # uses: yuzhiyongcn/setup-maven@0c5810c65a0fb6c88b6089724cc47370cf4eaffc
#         uses: yuzhiyongcn/setup-maven@v1.0.0
#         with:
#     # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
#           maven-version: 3.8.2
#       - name: Execute tests
#         run: |
#              cd democalculator
#              java -jar cucumber-tc-execution-engine-1.0.jar Agent_2 --spring.config.location=application2.properties
#       - name: Merge reports
#         run: |
#              cd democalculator
#              java -jar merge-cucumber-jar.jar  C:\\actions-runner\\_work\\GithubActionDemo\\GithubActionDemo\\democalculator\\target\\cucumber-reports Agent_2
