name: demo github actions
#on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  windows1:
    runs-on: 
      - Agent_1
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'        
          java-package: jdk
          server-id: github
          jdkFile: C:\Program Files\Java\jdk-1.8
      - name: Install Maven
  # You may pin to the exact commit or the version.
  # uses: yuzhiyongcn/setup-maven@0c5810c65a0fb6c88b6089724cc47370cf4eaffc
        uses: yuzhiyongcn/setup-maven@v1.0.0
        with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          maven-version: 3.8.2
#       - name: Install dependencies
#         run: |
#              cd democalculator
#              mvn clean install -DskipTests=true 
#       - name: Run tests in parallel
#         run: |
#             cd democalculator
#             chmod +x ./run_test.sh
#             tr -d '\r' <run_test.sh> test.sh
#             sudo chmod 777 test.sh
#             ./test.sh
            

#       - name: Upload test results
#         uses: actions/upload-artifact@v2
#         with:
#           name: test-results
#           path: target/cucumber-reports
  windows2:
    runs-on: 
      - Agent_2
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'        
          java-package: jdk
          server-id: github
          jdkFile: C:\Program Files\Java\jdk-1.8
      - name: Install Maven
  # You may pin to the exact commit or the version.
  # uses: yuzhiyongcn/setup-maven@0c5810c65a0fb6c88b6089724cc47370cf4eaffc
        uses: yuzhiyongcn/setup-maven@v1.0.0
        with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          maven-version: 3.8.2
      - name: Install dependencies
        run: |
             cd democalculator
             mvn clean install -DskipTests=true 
      - name: Run tests in parallel
        run: |
            cd democalculator
            chmod +x ./run_test.sh
            tr -d '\r' <run_test.sh> test.sh
            sudo chmod 777 test.sh
            ./test.sh          

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/cucumber-reports
