name: parallel tests
#on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
jobs:
  parallel-tests:
    strategy:
      matrix:
        runner:
          - label-1
          - javaversion
    
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'        
          java-package: jdk
          server-id: github
          jdkFile: /usr/lib/jvm/java-11-openjdk-amd64
      - name: Install Maven
  # You may pin to the exact commit or the version.
  # uses: yuzhiyongcn/setup-maven@0c5810c65a0fb6c88b6089724cc47370cf4eaffc
        uses: yuzhiyongcn/setup-maven@v1.0.0
        with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          maven-version: 3.8.2
      - name: Install dependencies
        run: |
             cd democalculator
             mvn clean install -DskipTests=true 
      - name: Run tests in parallel
        run: |
            cd democalculator
            mvn verify -Dcucumber.options="--tags @add --tags @subtract" -Dglue=org.example.stepdefs -Dplugin=json:target/cucumber-reports/Cucumber.json -Ddataproviderthreadcount=3
            

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/cucumber-reports
