name: parallel tests
#on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
jobs:
  parallel-tests:
    strategy:
      matrix:
        runner:
          - label-1
          - javaversion
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          cache: maven
          java-version: |
            8
            11
      - name: Setup Maven Action    
        uses: s4u/maven-settings-action@v2.8.0
        with:
          java-version: 11
          maven-version: 3.6.3
      - name: Install dependencies
        run: |
             cd democalculator
             mvn -B clean install -DskipTests=true
      - name: Run tests in parallel
        run: |
            cd democalculator
            mvn -B verify -Dcucumber.parallel.threads=3 -Dcucumber.filter.tags="@smoke" -Dcucumber.features=src/test/resources --plugin com.github.temyers:cucumber-jvm-parallel-plugin:5.0.0:generateRunners

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/cucumber-reports
