name: parallel tests
#on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
jobs:
  parallel-tests:
    strategy:
      matrix:
        runner:
          - label-1
          - javaversion
    
    runs-on: ${{ matrix.runner }}
    env:
      JAVA_HOME_11_X64: '/usr/lib/jvm/java-11-openjdk-amd64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache JDK
        id: cache-jdk
        uses: actions/cache@v3
        with:
          path: ${{ env.JAVA_HOME_11_X64 }}
          key: ${{ matrix.runner }}-jdk-11
          restore-keys: ${{ matrix.runner }}-jdk-
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: '11'        
          java-package: jdk
          
      - name: Check default Java version
        run: |
             java -version
             $ENV:GITHUB_PATH

      - name: Check installed/cached Java version
        run: java -version
      - name: Install dependencies
        run: |
             cd democalculator
             mvn -B install --no-transfer-progress --file pom.xml 
      - name: Run tests in parallel
        run: |
            cd democalculator
            mvn verify -Dcucumber.parallel.threads=3 -Dcucumber.filter.tags="@smoke" -Dcucumber.features=src/test/resources --plugin com.github.temyers:cucumber-jvm-parallel-plugin:5.0.0:generateRunners

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/cucumber-reports
